# Generated by Django 4.2.1 on 2023-05-26 07:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0002_user_is_online'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='thread',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='thread',
            name='first_person',
        ),
        migrations.RemoveField(
            model_name='thread',
            name='second_person',
        ),
        migrations.DeleteModel(
            name='ChatMessage',
        ),
        migrations.DeleteModel(
            name='Thread',
        ),
    ]
